### ISSUE TITLE
tab missing in sensor.py

### ISSUE THREAD

**Issue by turnmike2** [golles/Home-Assistant-Sensor-MC66C#10]
Hi,

I know your stopped the support on the repo. But I noticed allready with previous files and also with latest release a tab is missing.
This will cause HA to stop rebooting (due to errors in a file) or causing "not available" sensors.

Could you check line 97 in sensor.py? 
If a tab is added before "raise Exception('Received invalid datafield length')" the error is gone and system will run normally (at least on my system).

Thanks.
michel

**Comment by golles** [comment]
Also, proper checks have been added to prevent this from happening in the future.
