### ISSUE TITLE
Make platform mc66c suitable for energy dashboard

### ISSUE THREAD

**Issue by MCdobber** [golles/Home-Assistant-Sensor-MC66C#12]
### The request

Can you make the project suitable for energy dashboard, the platform don't allow state_class.
If you need some information let me know.

**Comment by golles** [comment]
The `Energy` sensor, with unit `GJ`, can since Home Assistant release 2022.11 directly be added to the energy dashboard. It's important to understand that you need to add this in the individual devices section. So not in the electricity or gas section. The devices here will be added on the bottom of your energy dashboard in a horizontal bar graph showing all your devices in `kWh`. This is by design and can't be changed by this component.

**Comment by HAEdwin** [comment]
It's an option to add a template to configuration.yaml
![image](https://user-images.githubusercontent.com/82239374/206901248-9df955b1-22ae-4cd6-8270-2d4ced37c951.png)
After restart you can add the new sensor to the energy dashboard and even specify costs.
![image](https://user-images.githubusercontent.com/82239374/206901489-f6179da9-fef7-48df-ba6c-0f0ae32ee646.png)
This isn't the best solution though,.. I think more people should request HA for adding GJ (district heating) to home assistant as a full fledged utility service just like gas, electricity, water.

**Comment by turnmike2** [comment]
Eventhough the info is somewhat strange, The projected data can be visable.
I added in configuration.yaml
```
homeassistant:
  customize_glob:
    sensor.stadsverwarming_energy:
      device_class: gas
      state_class: total_increasing
```

This resulted in a selectable option in Gas (but shows the strange warning), still you can use it:
![2022-12-12 21_19_35-Instellingen – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/58710889/207146642-654e889a-649a-485d-8980-a664c4b354b7.png)

With in the end:
![2022-12-12 21_24_26-Energie – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/58710889/207147077-55508352-c554-4b57-9546-9940cc295714.png)

As 1 Gj = 278kWh = 31,6M3 the total calculations will still be the same. (in the screenprint +/-46,6eur)
But I agree it would be nice if the class was adopted so it wouldn't show kWh but Gj.
