### ISSUE TITLE
HACS & ebay

### ISSUE THREAD

**Issue by Dinges28** [golles/Home-Assistant-Sensor-MC66C#6]
Hi Sander,

Not really an issue, but is it possible to adjust this repository that is will be able to import in HACS.
I already did read that you do not longer have this meter, but probably it is just a copy-paste from the other repo?

Also your link to ebay does not work, I'm trying to find a nice solution for my meter (and probably als try to adjust it to ESPHOME)

Thanks for your effort in advance

**Comment by golles** [comment]
That shouldn't be too difficult to do. I'll have a look this weekend.

About ESPHome, you might want to discuss with this person: https://gathering.tweakers.net/forum/list_message/68594280#68594280

**Comment by Dinges28** [comment]
> That shouldn't be too difficult to do. I'll have a look this weekend.
Really nice, thanks!

> 
> About ESPHome, you might want to discuss with this person: https://gathering.tweakers.net/forum/list_message/68594280#68594280

Did this guy do that already? I cannot find a post from him about that (or my searching on tweakers is not that good ;-) )

**Comment by golles** [comment]
You might need to dm him

**Comment by golles** [comment]
Hi @Dinges28 
I've added a [hacs.json](https://github.com/golles/Home-Assistant-Sensor-MC66C/blob/master/hacs.json) file, I hope this is enough to be able to import the repo in hacs. Let me know!

I've also removed the eBay link, it's not maintainable to keep a working link to an active seller.

**Comment by Dinges28** [comment]
Yes, that works like a charm, thanx
![image](https://user-images.githubusercontent.com/39988228/195284584-c9d67e3f-294b-475b-9de7-f3d0140eceda.png)

**Comment by golles** [comment]
Thanks you for confirming it works
